const provinces = [
    'Phnom Penh',
    'Kandal',
    'Kampong Cham',
    'Kampong Chhnang',
    'Kampong Speu',
    'Kampong Thom',
    'Kampot',
    'Koh Kong',
    'Kep',
    'Kratie',
    'Mondulkiri',
    'Oddar Meanchey',
    'Pailin',
    'Preah Vihear',
    'Prey Veng',
    'Pursat',
    'Ratanakiri',
    'Siem Reap',
    'Sihanoukville',
    'Stung Treng',
    'Svay Rieng',
    'Takeo',
    'Tbong Khmum',
    'Preah Sihanouk',
    'Banteay Meanchey',
    'Battambang',
];

export default provinces;